name = "ReachableControls"
uuid = "8de17bde-f6d6-45f6-ad07-262d79cdb311"
authors = ["Jonnie Diegelman <jonniediegelman@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
TaylorModels = "314ce334-5f6e-57ae-acf6-00b6e903104a"

[compat]
ConcreteStructs = "0.2"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
